import { Metadata } from 'next'
import { notFound } from 'next/navigation'
import AuditResults from '@/components/audit/AuditResults'
import ShareButton from '@/components/audit/ShareButton'
import { AuditResult } from '@/types'
import { Zap } from 'lucide-react'
import Link from 'next/link'

interface Props {
  params: { id: string }
}

const getAudit = async (
  id: string
): Promise<AuditResult | null> => {
  try {
    const res = await fetch(
      `${process.env.NEXT_PUBLIC_APP_URL}/api/audit?id=${id}`,
      { cache: 'no-store' }
    )

    if (!res.ok) return null

    return res.json()
  } catch {
    return null
  }
}

export async function generateMetadata({
  params,
}: Props): Promise<Metadata> {
  const audit = await getAudit(params.id)

  if (!audit) {
    return {
      title: 'Audit not found — SpendLens',
    }
  }

  const savings = audit.totalMonthlySavings.toFixed(0)

  const title =
    savings === '0'
      ? 'My AI stack is already optimized — SpendLens'
      : `I could save $${savings}/mo on AI tools — SpendLens`

  return {
    title,
    description: `See my full AI spend audit. ${
      audit.aiSummary ?? ''
    }`,
    openGraph: {
      title,
      description:
        'Free AI spend auditor by Credex. Find out if your team is overpaying.',
      url: `${process.env.NEXT_PUBLIC_APP_URL}/audit/${params.id}`,
      siteName: 'SpendLens by Credex',
      type: 'website',
    },
    twitter: {
      card: 'summary_large_image',
      title,
      description: 'Free AI spend auditor by Credex.',
    },
  }
}

export default async function AuditPage({
  params,
}: Props) {
  const audit = await getAudit(params.id)

  if (!audit) notFound()

  return (
    <main className="min-h-screen bg-background">
      <header className="border-b border-border bg-background/80 backdrop-blur sticky top-0 z-10">
        <div className="max-w-2xl mx-auto px-4 py-3 flex items-center justify-between">
          <div className="flex items-center gap-2">
            <div className="w-7 h-7 rounded-md bg-primary flex items-center justify-center">
              <Zap
                size={14}
                className="text-primary-foreground"
              />
            </div>

            <span className="font-bold text-sm">
              SpendLens
            </span>
          </div>

          <Link
            href="/"
            className="text-xs text-muted-foreground hover:text-foreground underline"
          >
            Run your own audit →
          </Link>
        </div>
      </header>

      <div className="max-w-2xl mx-auto px-4 py-10 space-y-6">
        <div className="space-y-1">
          <h1 className="text-2xl font-black">
            Shared Audit Report
          </h1>

          <p className="text-sm text-muted-foreground">
            This audit was generated by SpendLens.
            Personal details have been removed.
          </p>
        </div>

        <ShareButton auditId={audit.id} />

        <AuditResults
          audit={audit}
          onCaptureLead={() => {
            window.location.href = '/'
          }}
        />

        <div className="text-center pt-4">
          <Link
            href="/"
            className="text-sm text-primary underline font-medium"
          >
            Run your own free AI spend audit →
          </Link>
        </div>
      </div>
    </main>
  )
}